name: Build Image

on:
  push:
    branches:
      - develop
      - main

env:
  aws_region: ${{ vars.AWS_REGION }}
  dockerfile_path: fido2-demo/demo/Dockerfile
  container_image_uri: 911167901271.dkr.ecr.us-east-2.amazonaws.com/detentora/fido-server
  environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'sandbox' }} 
  
permissions:
  contents: read

jobs:
  setup:
    name: Get references
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
      datetime: ${{ steps.datetime.outputs.datetime }}
    steps:
      - name: Get git SHA short
        id: sha
        run: echo "sha=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Get datetime
        id: datetime
        run: echo "datetime=$(date --utc +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ env.container_image_uri }}"
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ env.environment }}-${{ needs.setup.outputs.datetime }}
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ env.environment }}-${{ needs.setup.outputs.sha }}

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.dockerfile_path }}
          context: .
          build-args: |
            TAG=${{ env.environment }}-${{ needs.setup.outputs.sha }}
          tags: |
            "${{ env.container_image_uri }}:${{ env.environment }}-${{ needs.setup.outputs.datetime }}"
            "${{ env.container_image_uri }}:${{ env.environment }}-${{ needs.setup.outputs.sha }}"
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      - name: Set image tag
        id: set-image-tag
        run: echo "image_tag=${{ env.container_image_uri }}:${{ env.environment }}-${{ needs.setup.outputs.sha }}" >> $GITHUB_OUTPUT
